curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01352-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01281-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02220-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01220-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01313-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01286-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01091-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01976-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00380-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02544-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00149-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00834-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02352-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01086-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01102-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02066-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01806-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00312-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00991-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02945-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02266-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01085-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00380-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01213-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00908-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00369-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01088-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01081-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02201-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01082-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00910-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01828-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00380-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01607-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00491-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01646-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00817-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00246-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01281-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00908-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00792-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00813-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00183-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02332-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01279-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01828-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01179-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00194-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01989-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00150-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01465-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01905-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01808-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00646-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02429-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01200-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01654-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00026-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02761-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02214-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01902-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02070-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01083-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02066-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00491-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01283-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00369-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01524-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02857-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00573-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00831-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00320-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00646-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02352-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02068-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00817-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01102-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00647-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00165-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02726-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01808-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01656-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01102-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00314-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03020-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01976-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00448-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01648-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01081-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02160-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01655-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01086-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00390-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00789-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00980-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01287-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02726-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01220-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00320-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02248-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01603-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00246-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00789-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02551-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02577-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00832-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02248-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01869-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02338-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02811-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00168-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02544-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00437-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02265-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00183-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01214-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01885-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03018-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00799-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01648-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02211-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00646-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01106-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00607-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02063-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02431-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02224-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00790-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01213-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01077-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00011-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01648-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00369-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02005-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00088-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02005-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01651-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01033-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03019-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01951-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00976-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01553-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00908-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01078-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00359-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00910-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01175-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00177-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02211-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02726-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00991-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01083-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00733-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00380-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02857-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02248-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00313-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00242-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00244-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00097-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02085-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00242-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01213-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02063-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00317-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02082-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02160-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02066-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00902-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02160-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02085-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00148-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00390-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00733-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01107-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02723-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01806-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02005-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01978-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02429-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00103-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00097-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02723-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00103-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02214-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01929-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00982-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00765-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02811-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00491-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01106-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01836-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01090-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01808-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00715-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01090-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02439-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01976-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01091-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00418-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00310-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00790-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00183-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01214-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00581-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00390-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01536-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00577-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00312-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01200-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01083-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00494-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00815-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01524-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00165-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01654-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01081-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01078-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01106-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00581-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00150-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01083-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02364-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00494-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00165-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01107-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00733-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02842-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03018-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02761-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01090-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00416-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01080-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00154-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02439-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01078-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02015-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01085-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02429-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00149-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01806-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02070-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02346-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01954-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00310-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01665-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01861-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01200-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01078-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01603-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00096-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00168-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02551-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00177-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01951-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01681-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02556-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00359-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01657-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00799-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00447-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01459-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01522-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01607-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01557-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01080-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01077-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02084-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02761-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01952-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00647-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02176-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00194-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01214-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00315-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01603-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00310-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01220-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03021-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00194-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00583-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01077-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00418-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00494-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00149-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00813-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00183-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00607-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00359-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00312-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02248-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01082-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00165-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00447-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00011-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02364-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00647-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01536-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01522-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00010-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00447-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00148-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00831-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01286-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02577-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00244-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02439-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01302-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02556-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01178-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01557-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00583-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00953-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01180-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02220-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00148-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00917-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00991-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03021-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-03019-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00148-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02177-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02332-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01665-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00495-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00194-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00610-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02202-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02346-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00154-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00149-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00246-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01261-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01861-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01560-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01179-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01657-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01646-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00103-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01902-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02264-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00317-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00733-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00194-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01651-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01081-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02015-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02723-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00447-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00573-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00360-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00177-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01287-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02201-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01836-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01655-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00244-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00416-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00953-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00852-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00577-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01085-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01077-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01083-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00646-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02220-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00834-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01885-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01603-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01220-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02431-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00982-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01464-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02224-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00168-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00390-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00581-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01681-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02556-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00815-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00812-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01176-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01361-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00305-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00418-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01470-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00494-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00150-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01470-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01963-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01649-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00610-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01091-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00492-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00814-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01107-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00606-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01352-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00953-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02070-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01083-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00313-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00495-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02175-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01522-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01178-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01462-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00910-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02332-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00577-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00573-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02364-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00317-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01656-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01081-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01989-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00177-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00573-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00305-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01082-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00154-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02332-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01536-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00314-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00573-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00494-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00606-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01808-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00953-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00812-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01676-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00583-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02160-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00313-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01524-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01665-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01657-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01281-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02160-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00359-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01200-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00183-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02431-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00154-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00149-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01861-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01034-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00317-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01905-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02841-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01806-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01976-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01261-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00168-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01213-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01287-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01034-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00765-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00320-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02263-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02338-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02544-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00390-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00492-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01808-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02346-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01978-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00165-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00154-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00149-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01080-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00646-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02224-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01088-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02224-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00561-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01090-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01869-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02763-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00491-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01976-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01649-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02763-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00088-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00907-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00583-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02856-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01885-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00079-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01828-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01091-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00154-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01077-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00991-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02841-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00991-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00766-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01524-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02015-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01085-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00968-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01088-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01082-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00831-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01080-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00314-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01279-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00982-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01836-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00244-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01560-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00390-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01361-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01869-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00902-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02723-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01649-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01882-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01656-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00796-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00647-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00495-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01091-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02175-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01462-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02842-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02262-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00242-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01607-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01954-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00168-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01078-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00437-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00380-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02439-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02220-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01088-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00096-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00150-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00976-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00320-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01828-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01200-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00315-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02263-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00244-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02346-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00852-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01978-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01607-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01522-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01175-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01553-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02352-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01286-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01861-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00312-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02202-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02084-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00026-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01078-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01261-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01288-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01288-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01681-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02553-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01178-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00573-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01261-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00165-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00907-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01180-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02726-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00491-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00715-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01082-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00183-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00814-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01085-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00079-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02063-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02208-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00246-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01978-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00168-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00004-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00800-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00980-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00966-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00796-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01651-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00148-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01976-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02945-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00791-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01536-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00194-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00800-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01681-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01279-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00969-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02063-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01958-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02068-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02265-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01963-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02248-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00310-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01085-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00581-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00148-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02160-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00004-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02224-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01989-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00646-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00721-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00380-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02068-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02015-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01176-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00320-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00314-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02338-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00917-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02082-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01080-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02945-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00317-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00647-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00360-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00150-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00088-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00733-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00313-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00852-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00561-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00416-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01086-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01088-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02577-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00953-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01088-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00360-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01034-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01869-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01882-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00437-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00150-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01654-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00369-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02544-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01091-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00177-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01464-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00312-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02082-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02556-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00907-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00902-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01082-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00448-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00315-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01080-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00981-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00315-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01905-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00437-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02084-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01086-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01989-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01465-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00982-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01090-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01279-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01179-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00970-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02262-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01352-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00791-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02177-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00418-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01313-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01361-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02208-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01287-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01086-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00577-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00917-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02763-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00647-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01033-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00492-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01978-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02856-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00492-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00577-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00981-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00976-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01885-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00606-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00606-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02085-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01806-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00103-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02176-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00577-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00435-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00766-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02945-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02945-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01978-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00991-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02551-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01902-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00792-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01214-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00721-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01077-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00246-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02811-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00852-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02224-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00010-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01646-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00907-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01929-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00310-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01302-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01836-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01081-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01086-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-01200-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00982-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00492-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-02551-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02338-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01286-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02264-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00976-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00561-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01281-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-00314-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-01033-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3N-02811-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CCRCC/C3L-00982-22.svs
