curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03239-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00629-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01495-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04142-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01533-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01494-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00179-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00382-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00209-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01492-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03223-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01494-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00874-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03614-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04787-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02373-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02035-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02330-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05027-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02035-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03223-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00385-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03377-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00967-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05175-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03374-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05175-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01492-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04760-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03916-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-01063-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00378-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01495-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00209-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00376-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01492-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02102-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05554-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00384-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02324-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01493-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04294-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03239-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04733-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03229-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00382-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00327-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01844-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02026-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01494-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03885-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03381-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02035-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02373-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00874-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03235-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02270-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01841-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04142-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05554-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01533-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03229-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02026-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01481-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00209-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00629-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00275-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00967-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02330-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02679-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02373-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03382-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00432-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00378-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02270-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02102-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04156-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02102-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02324-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03029-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02615-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03382-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01844-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03228-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01494-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02033-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03916-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00629-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01493-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04787-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05027-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01481-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04787-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02615-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02633-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02327-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00989-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00967-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04760-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03885-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05554-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00989-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03228-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01530-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01481-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01495-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03220-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05527-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05175-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02040-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04156-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02615-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00432-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02033-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02373-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02102-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00209-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03913-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01841-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00967-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03239-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02633-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00989-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00378-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03918-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00434-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03364-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04733-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03460-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00327-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01495-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03234-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03913-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03229-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03235-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05229-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02033-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03913-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04733-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03220-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03234-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01824-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01494-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02270-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00384-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05175-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03235-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00179-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05517-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04156-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00179-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03885-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03913-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03916-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00179-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02335-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04787-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01841-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00434-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00327-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01481-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04011-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03364-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05527-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02270-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05554-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03617-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05517-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03362-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03223-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00967-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01844-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-01063-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00378-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00382-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01493-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00220-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02615-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00376-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03918-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04293-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02026-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01824-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03918-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00989-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00385-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03220-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00434-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01492-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04760-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00434-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01824-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01493-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00275-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03617-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02270-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01530-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02330-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04787-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04760-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02330-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03374-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01533-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00220-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01841-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03239-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02335-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03614-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03381-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00385-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02026-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03377-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02040-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05517-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01495-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02327-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00376-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02679-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01493-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03460-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00382-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02647-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02327-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05527-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01533-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01494-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00220-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00376-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02327-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03381-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03885-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03229-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03097-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01481-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00220-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02335-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01844-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05229-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04142-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04156-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03235-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03364-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04011-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03916-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02324-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01530-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02615-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03382-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04331-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04011-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03362-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00179-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03460-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02033-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03374-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00327-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03228-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05299-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00385-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05229-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03234-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04212-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01530-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02335-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03614-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00209-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00220-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03367-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00967-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03362-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02040-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00432-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01845-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03617-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02040-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03367-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01495-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01492-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04733-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04011-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01824-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01493-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05302-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00376-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00382-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05229-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03617-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03228-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02102-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00629-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00384-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-00275-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03614-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04733-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00327-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-04142-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00220-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04011-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03460-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00209-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-02622-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03223-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03234-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-01481-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00327-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-05262-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00384-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00179-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-00432-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-03377-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3L-04760-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03220-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-02324-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/CM/C3N-03918-21.svs
