curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03187-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03968-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02782-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02644-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00424-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01850-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04092-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02770-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02682-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01852-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03260-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03747-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04339-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02041-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01046-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01517-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03473-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02704-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04539-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01856-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02783-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01518-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03484-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01043-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02783-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00661-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02784-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04090-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00019-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02681-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02706-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02706-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03757-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01818-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03405-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01049-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04094-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03372-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04359-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02783-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04090-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01857-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04082-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00424-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01834-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03187-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04084-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02662-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00019-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00591-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03001-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01849-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03800-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04213-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01048-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02705-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03184-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00424-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04362-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03727-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00674-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02181-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03744-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01370-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01040-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03747-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01815-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01192-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03473-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00278-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03473-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03810-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02707-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04092-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00528-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02644-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03791-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03392-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04082-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03182-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02984-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02642-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03744-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02644-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04362-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02705-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01046-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03372-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02783-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00662-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02183-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00591-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03681-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03183-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02465-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03484-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04795-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03390-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02183-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01515-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04092-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02708-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03184-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04339-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01043-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02788-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00429-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01155-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03747-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02984-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00674-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02181-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02769-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04359-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02984-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00671-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02642-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04084-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04362-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01197-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03939-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01368-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03800-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02704-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01364-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03182-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04359-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01367-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04098-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01334-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02662-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02705-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03791-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02984-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03003-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03387-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04213-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04795-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02181-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03735-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03182-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00349-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02185-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02504-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00663-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02707-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02662-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01798-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03800-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01850-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03935-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02785-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02642-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04362-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00265-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02542-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04359-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01798-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03744-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02705-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01518-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03184-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03070-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04097-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00636-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04339-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00671-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02970-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02644-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02190-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03939-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03188-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00265-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00661-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00671-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03935-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03802-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00278-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04113-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01146-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04795-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02704-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01142-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02662-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04090-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03088-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00591-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00265-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03186-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03405-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00665-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01156-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03968-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03070-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03755-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01369-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01518-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04083-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02190-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04098-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02900-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02707-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03939-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02769-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03968-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02784-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01849-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00636-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02707-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03748-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03001-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03968-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01839-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03756-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00662-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02642-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04083-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01849-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02970-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01839-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03407-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04731-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03390-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03756-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04083-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01045-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01192-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01798-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02705-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00663-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04731-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02256-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00265-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01061-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04084-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00016-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02188-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04312-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02785-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00528-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00016-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00278-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01366-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01814-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01517-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03791-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01849-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02786-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02788-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03088-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03748-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04113-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04083-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02783-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01505-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03183-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00662-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01818-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04098-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04038-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02186-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00016-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03748-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02708-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00636-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02186-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04094-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00429-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03810-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01370-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03387-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02708-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03480-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03392-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04312-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04213-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01157-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02706-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03480-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02255-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02542-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04731-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03187-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01048-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02788-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00104-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00631-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00663-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04312-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01157-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03797-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02785-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04213-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02644-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02465-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04362-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03407-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02706-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01814-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01815-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01334-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00661-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00661-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03797-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04339-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02542-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01154-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02769-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03407-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04038-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01149-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02704-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01851-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02183-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00528-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01196-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03186-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01142-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03797-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01816-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00506-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02683-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03789-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00665-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02970-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04097-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02190-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01146-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02786-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03180-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03453-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03728-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00349-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01366-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04731-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04731-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03003-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04038-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00016-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01327-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04090-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03407-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03810-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03183-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04359-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00665-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03407-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03748-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04084-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00019-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03180-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02955-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04339-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04537-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04082-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02662-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00677-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02784-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04038-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02186-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03266-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04795-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03968-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01817-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01155-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00429-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03449-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01154-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00665-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01517-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04795-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01817-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02707-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03681-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00349-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02704-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00631-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01857-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03757-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02185-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01049-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03802-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02642-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03001-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04038-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04083-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02188-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02708-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03025-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02504-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03681-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03400-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03400-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03802-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03180-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01156-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03480-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01364-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03188-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04113-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01061-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01045-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01816-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02188-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03188-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04213-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01040-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00349-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-03681-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03935-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02185-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02786-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00506-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04094-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01887-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01815-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03186-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01814-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03003-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00677-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-03001-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-01149-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02041-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00365-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01852-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-04097-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-02706-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00506-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-04084-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02770-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-02770-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01368-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-00663-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3N-01818-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/GBM/C3L-00631-22.svs
