curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04275-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02275-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03458-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01340-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01337-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04849-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03889-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03837-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00829-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03612-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04152-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02713-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00987-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03888-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03889-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00846-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01754-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00829-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00299-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00846-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04277-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00825-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00295-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01752-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00987-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03841-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04844-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03042-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01756-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03487-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03620-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04611-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01947-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03878-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03490-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04849-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03027-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01944-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01754-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02275-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01755-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00204-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02695-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01338-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02716-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01946-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00307-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01645-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01337-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03619-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00498-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00987-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03433-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00297-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01945-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03490-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03876-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01756-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01338-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03011-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03612-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00299-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00306-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00829-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03457-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03933-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04153-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03928-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03837-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03488-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00999-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00306-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01757-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00987-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03785-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03619-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02714-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01758-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01754-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00295-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03488-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03226-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00498-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00299-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02333-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04152-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00871-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-01237-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03785-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00995-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04275-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01339-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03013-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03226-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00204-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00204-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03487-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00295-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04276-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00299-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04844-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00306-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04273-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03933-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02727-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01338-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03487-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03933-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03664-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04279-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03849-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03878-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01757-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03782-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03490-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02713-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03664-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01758-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00999-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04273-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00994-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00307-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02714-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04153-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00498-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00995-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03027-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02695-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01340-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02727-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00828-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03015-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00987-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03008-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00299-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00994-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01643-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02700-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-03378-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00994-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00977-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03487-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01643-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01758-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04844-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00295-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02695-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00829-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03456-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03009-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04611-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03783-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00828-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00306-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01757-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02700-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00204-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04153-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03612-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02716-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04273-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00995-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03619-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03042-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00999-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00519-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03490-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03009-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01339-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01858-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00519-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-01237-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00498-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03015-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00307-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00828-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03928-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03012-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03781-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03009-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01943-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03612-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02727-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04278-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01340-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04276-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00997-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01858-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03013-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03226-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02713-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00297-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04849-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00822-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03042-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02714-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03042-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01757-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04611-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03011-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02279-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03042-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00871-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00204-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02714-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01754-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03011-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01945-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02713-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01859-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00498-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00846-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03620-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03488-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00995-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01337-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02694-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02700-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00995-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02693-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01947-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02694-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02730-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01754-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02700-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03878-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00997-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04152-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03620-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00994-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02727-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00307-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02925-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03045-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02693-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03928-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00995-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01620-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03011-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03889-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03928-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-01138-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00297-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00871-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03012-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01645-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03028-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00987-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02730-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01948-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04279-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00297-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00825-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04280-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00825-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00295-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00828-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03888-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02925-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02621-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01755-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01620-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01620-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03619-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03841-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03849-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03008-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03888-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03433-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02333-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03781-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00846-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00857-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04278-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00994-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00204-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02333-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03782-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00519-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01758-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00828-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00306-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01948-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03226-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03841-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03933-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-03378-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03837-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03620-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02617-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00297-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02730-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03889-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01752-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01645-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03876-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04025-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02925-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03488-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00822-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00519-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04277-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01755-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02279-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02716-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01858-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01946-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04152-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01757-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00857-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03458-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03783-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00307-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00997-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04611-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01948-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04354-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01859-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01944-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03664-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-04153-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00829-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00977-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00857-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01945-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02275-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01943-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03888-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01943-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03045-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00519-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03876-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03028-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-01339-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03457-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-01138-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-00822-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-04791-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03042-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03849-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-02651-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-03664-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3L-00994-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/HNSCC/C3N-02333-22.svs
