curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01411-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03272-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01893-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00503-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00965-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01017-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02426-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02546-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03093-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02435-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02964-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03425-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03851-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03848-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00839-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03076-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02127-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00445-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00927-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02425-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02285-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01017-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01411-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02289-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02374-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02546-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01017-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02163-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00568-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01025-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02170-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01285-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02725-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00839-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01411-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02168-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02963-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00445-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00993-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00247-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00503-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00445-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02164-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01455-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00309-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02127-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01025-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02284-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03204-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03882-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00839-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00993-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03092-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00415-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01018-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02339-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03880-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00503-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01411-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00993-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02434-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02252-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02675-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02969-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02164-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00927-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02425-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01194-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03851-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02891-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01028-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03093-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03272-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01017-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03486-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00445-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03093-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03875-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01028-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02130-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00415-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02252-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03848-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01020-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03662-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00211-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02130-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00503-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02130-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01455-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00211-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02435-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02951-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03886-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03875-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02725-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04124-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01018-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02969-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00503-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03880-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02434-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03204-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02374-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02963-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01455-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02288-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02891-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02130-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01000-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02164-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02168-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02170-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03486-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03882-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00568-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02968-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00603-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03092-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00081-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02968-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00993-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01893-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02725-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04155-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02964-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00415-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00247-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01846-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00555-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02358-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01028-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00927-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03072-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02339-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02523-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04127-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01285-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01025-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02426-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02552-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02284-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02434-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00503-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02375-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00211-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02494-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00603-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01018-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01028-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03886-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00309-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04124-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02163-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00904-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01892-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02349-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01838-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01020-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01025-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03662-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00309-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03424-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01455-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01892-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00965-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04124-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00965-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02168-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02283-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02575-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02963-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01846-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02494-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03092-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00555-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04391-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02349-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00497-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00247-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02127-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01020-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04162-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02552-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01884-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02300-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01285-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02358-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01020-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02163-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00839-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03886-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02494-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00568-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04391-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02425-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02374-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01606-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03678-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03678-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01455-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03875-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04071-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00923-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01028-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02168-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04162-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02650-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00211-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03051-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02434-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02435-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01028-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03051-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00993-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01892-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03076-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03877-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00568-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01017-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03072-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01663-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00965-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03076-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01000-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03204-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01884-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00927-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03882-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04155-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02130-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03851-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04162-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00309-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00965-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00904-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03486-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02951-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02575-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02170-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01018-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04127-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01838-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01194-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02725-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03272-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02163-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00445-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00445-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01025-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04391-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02284-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01000-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02168-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02163-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03092-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00555-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02494-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04071-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02127-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02283-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00211-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01846-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02164-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03425-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03272-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03877-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00993-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01455-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03441-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02969-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03093-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02523-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04162-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03424-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03072-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03272-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01884-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02426-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03092-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01025-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04071-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00555-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03877-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03486-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02289-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00247-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02130-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02358-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03662-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02951-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04155-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02619-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03441-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00497-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02339-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02127-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02964-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02300-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04013-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03962-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02665-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03662-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00555-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03093-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03678-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01884-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03272-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04155-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02552-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02285-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02170-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01846-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02300-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02523-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00211-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03963-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00555-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02646-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02546-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03886-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03961-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00603-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01411-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00309-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02435-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02963-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04014-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01020-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01020-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02170-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02434-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01663-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02624-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02283-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03093-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03880-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01411-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02164-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-04071-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02669-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02358-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02891-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02288-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03848-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02127-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02649-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02168-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02575-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02625-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02285-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02435-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-03965-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03092-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01018-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00247-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-04127-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01018-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00923-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01663-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02523-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02629-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02675-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02375-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-00221-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00904-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02339-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02660-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01606-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-02375-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00081-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-03051-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01893-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-00965-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02648-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3N-01017-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-02627-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LSCC/C3L-01285-22.svs
