curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01416-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03726-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03222-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02586-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03462-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03262-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02230-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03057-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03268-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02348-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00180-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01862-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03202-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01683-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02380-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02158-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02365-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03268-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02948-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01417-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01413-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01415-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00893-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02919-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02145-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02144-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02421-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00578-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02145-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04157-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03420-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00738-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02242-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00556-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02145-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02141-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01072-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01019-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02929-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00556-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03726-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00279-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02242-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03038-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02549-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00549-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02089-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02601-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02165-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01330-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02729-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00294-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02916-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01417-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02146-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02281-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02957-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02237-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02721-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02242-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00704-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02153-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02145-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01030-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00578-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02003-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00549-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02153-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00578-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03057-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00199-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02290-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02149-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00579-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02718-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00545-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02529-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02169-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02926-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02088-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00140-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00572-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01414-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00550-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02088-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00167-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00180-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01632-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03233-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02893-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03929-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03462-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00559-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00572-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03271-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01330-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00175-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02150-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01074-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02572-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00550-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01023-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02967-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00293-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00140-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01682-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00560-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02586-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00180-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02424-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02513-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00913-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00217-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02348-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00559-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01417-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02345-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02365-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02237-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01842-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04176-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00556-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03271-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02529-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02088-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02003-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02141-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03238-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01074-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04173-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04382-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02572-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01410-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01074-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03063-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03921-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00547-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01823-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03271-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00556-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00095-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00580-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02928-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02718-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00556-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02169-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03721-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02150-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02424-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02973-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00293-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03205-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03205-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02587-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00574-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00167-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04382-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03764-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03911-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00604-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02219-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01072-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02158-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02379-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02424-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02158-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00422-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00551-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01030-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01632-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02149-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03726-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00574-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02000-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00913-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00095-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00560-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02916-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01023-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00169-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02423-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01016-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02251-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00444-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01488-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01022-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00545-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01405-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00580-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02144-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03238-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00738-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03726-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02089-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02672-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02828-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00737-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03225-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01021-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00552-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03262-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01417-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01074-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02087-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01889-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02893-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03262-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02165-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02549-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02000-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00294-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01489-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02143-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00279-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03911-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02090-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02957-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02916-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00510-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02757-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02718-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03726-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00547-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03262-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00169-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02090-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02088-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03073-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01409-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01330-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02141-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03212-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02828-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00545-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01419-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02365-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00368-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01413-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02928-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02515-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01409-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02582-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03238-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02728-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02169-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00294-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03212-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02948-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01415-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01024-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00422-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00959-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01414-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00422-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02920-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01410-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02515-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01488-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00175-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03052-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02345-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02149-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01862-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02149-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02152-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00422-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03233-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03073-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00546-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01409-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00737-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02919-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02234-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01071-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00203-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02237-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03911-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02515-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02433-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02165-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01022-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01405-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01682-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03054-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01071-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03765-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02757-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02242-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03063-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02155-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01410-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01410-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02672-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02090-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02715-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02954-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00959-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00169-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01019-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02919-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00545-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03052-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01799-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01419-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02926-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02153-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03080-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02144-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00549-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00913-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00510-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02155-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02089-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02601-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01489-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03929-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02365-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00580-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02158-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00217-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02145-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00580-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01023-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02089-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01410-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00094-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02165-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00169-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00560-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01419-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01414-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00580-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01016-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02234-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01419-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03233-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00560-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02155-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02230-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02155-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03890-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02508-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02508-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01409-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00169-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02423-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02957-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02150-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02153-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01414-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00279-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02923-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01682-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02513-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02508-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00368-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02169-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03721-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00547-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02143-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04180-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02834-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03268-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02950-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00444-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04176-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01021-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00083-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02155-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03238-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01413-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00559-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02067-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02142-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02379-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00893-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04382-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02144-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02834-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00578-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02529-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02146-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00293-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02003-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00552-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02152-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00572-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03210-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02142-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02928-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02433-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02560-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01489-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01023-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00169-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02920-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02828-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00095-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01072-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00368-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00959-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02559-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00510-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02922-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04157-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02143-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02379-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02957-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00579-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02422-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02067-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02143-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04168-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01408-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02421-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00704-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01030-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02150-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02433-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00279-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03074-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03764-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01417-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00217-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02150-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02240-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00545-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00737-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01022-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02165-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03054-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02230-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02834-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00167-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00560-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00572-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02282-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02828-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01330-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02834-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00559-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02348-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01074-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03268-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03462-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01890-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02142-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03225-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01632-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02149-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03271-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02513-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00294-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02948-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02169-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00604-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03271-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01019-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00217-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02572-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00175-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02155-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00551-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02728-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01024-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02422-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02281-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02922-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03463-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02143-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03202-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02508-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00550-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00737-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01415-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00144-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02916-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03679-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03080-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02087-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02950-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01023-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02142-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02240-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03212-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02237-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02169-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02282-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02149-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00559-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02365-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00412-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02588-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03911-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01414-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00549-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02067-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02828-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01023-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01682-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02158-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02513-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01330-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02515-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01416-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00510-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00144-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03222-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01024-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01488-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02549-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03202-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03921-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01415-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03765-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03642-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00893-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02834-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00001-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02153-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02834-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02144-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00738-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02672-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01842-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02923-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02345-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02421-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04157-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00546-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02916-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00546-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02948-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00550-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02088-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02146-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02350-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02721-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02728-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01408-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00095-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01419-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01330-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01489-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00579-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03921-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00547-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01489-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00738-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01410-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01071-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02146-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03225-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01414-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00552-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01488-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02508-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00093-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00510-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02090-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01413-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00549-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00294-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01021-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01072-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04759-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02961-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03233-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02240-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00546-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00574-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02958-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02158-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02715-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01405-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02240-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03420-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03463-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00444-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01016-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00551-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00444-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02345-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02230-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00893-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00893-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02588-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02281-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02919-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02089-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01683-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01019-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00175-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02240-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00737-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02582-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02757-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02920-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03222-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03268-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01416-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01022-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01016-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02728-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00203-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00203-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00080-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01021-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04157-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03890-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02234-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00293-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00203-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02758-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01413-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00550-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00604-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00446-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01030-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04173-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03890-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00167-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02923-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00560-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02087-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00550-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01419-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00579-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00893-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00574-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02929-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02758-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00293-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00552-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03210-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00549-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01071-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02089-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02290-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00009-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02152-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02513-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00167-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00959-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03054-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02582-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01413-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00580-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02234-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01683-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01408-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00217-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00433-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01022-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02237-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02237-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02922-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02251-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02451-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02560-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02560-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01842-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02643-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00551-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02152-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00140-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02515-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02559-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02451-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03222-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04168-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01799-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00203-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02144-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00559-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00167-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03268-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01488-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00083-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02240-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01799-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02230-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01823-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00545-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01405-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02143-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01889-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00547-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00080-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02146-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02423-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02508-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02715-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03462-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00199-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01416-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02616-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03929-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04168-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02002-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01823-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02828-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00552-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00001-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02380-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00578-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02764-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03205-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03420-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00223-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02129-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02922-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00175-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02090-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02290-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02219-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01024-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01016-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02973-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02242-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00604-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00279-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02920-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02141-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00552-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00704-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03052-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02923-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03038-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00547-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02973-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01415-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00510-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02129-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01024-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02922-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03271-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03073-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02451-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01489-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01021-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02587-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00572-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00574-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02923-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02129-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03057-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01415-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03969-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02919-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00546-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00199-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00579-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01409-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00579-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00094-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02758-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02146-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04033-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04365-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02234-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02350-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02152-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03976-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03038-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00444-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00422-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00263-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01016-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00546-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02588-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01408-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01030-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02087-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02967-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03262-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02002-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02087-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04180-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01632-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02721-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00199-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02422-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02973-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00422-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02242-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00412-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00578-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02721-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03225-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02192-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00973-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03679-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00556-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02920-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01862-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02729-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00203-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02153-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03038-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02922-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01072-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02920-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02150-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02715-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02954-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01823-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00444-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02230-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01408-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01021-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02764-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04037-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02380-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00574-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02219-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03642-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00175-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01022-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03985-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02923-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00009-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02973-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01408-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00180-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02000-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02961-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02141-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02929-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00572-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00217-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02152-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01488-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01416-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01890-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00199-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01799-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03717-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02587-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00551-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00093-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02950-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03074-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04168-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03210-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02948-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03074-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02919-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02718-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04757-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01405-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01019-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04040-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01019-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01071-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00279-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00704-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03921-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02145-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03063-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02586-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02251-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03984-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02958-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03929-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-04031-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02142-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03717-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00551-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02088-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00180-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01024-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02002-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03262-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00180-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01416-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01842-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03080-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02234-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01417-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01030-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-03890-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02926-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-04382-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02193-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-00959-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02950-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01074-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02729-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01924-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01072-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-00913-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02129-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02451-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02141-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02451-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02916-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01862-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02654-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01405-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-02661-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-02764-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3N-01071-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-01683-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/LUAD/C3L-03726-24.svs
