curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03356-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00625-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03388-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02295-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01382-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02613-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00928-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00881-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02589-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00514-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02592-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03666-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03190-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00302-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00017-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00189-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04475-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01328-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02971-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00640-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03630-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02897-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00954-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00395-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01900-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00017-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01637-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02109-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02590-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01719-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00277-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02604-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04283-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00401-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00622-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01997-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01998-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01689-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01971-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04283-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01502-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03632-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00518-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00249-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03039-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00198-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01971-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03350-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02606-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00401-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01381-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02944-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04126-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00819-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02899-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00518-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03129-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03853-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02997-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01124-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00511-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03126-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03440-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01380-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00277-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03123-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02585-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02940-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03173-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03039-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04080-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00516-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03440-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01502-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03388-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02606-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03884-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01453-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03086-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00277-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01715-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00885-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00513-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02997-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01598-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00511-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02606-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00303-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04284-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02109-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01328-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03371-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00017-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02010-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02069-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02940-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01054-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01453-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01158-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01037-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03394-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04080-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02591-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01053-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00395-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04495-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04495-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03639-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00512-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02463-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01375-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00198-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04119-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01598-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01160-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01662-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01971-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01389-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02939-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00516-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01169-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01160-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00436-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03126-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00598-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01702-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02573-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00511-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00885-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01124-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04473-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04475-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03356-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03129-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01637-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03780-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03039-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00518-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02010-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03439-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00957-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03630-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01997-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02939-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01900-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00928-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03371-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00303-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03639-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03743-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00640-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01383-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01054-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02592-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00885-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02899-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01380-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03430-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02944-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01389-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04479-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01388-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03628-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03211-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02971-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03394-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04475-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00277-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00511-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02890-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04473-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01328-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01662-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04072-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00302-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04080-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03394-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04284-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01689-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01388-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03350-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01897-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01053-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00598-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01703-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03426-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02118-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04282-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00436-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02463-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02592-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00819-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02971-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02112-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00303-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02069-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04080-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01637-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03371-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02585-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03665-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03743-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01036-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02463-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04853-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00303-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01051-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04495-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03624-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00302-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00589-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00640-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02610-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02118-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01012-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02768-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04119-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01168-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03211-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00198-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00517-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04848-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03628-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02579-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03778-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02613-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01158-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04126-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04853-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02463-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01031-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01689-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00881-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01900-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03839-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03780-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02295-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02890-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02116-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00622-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00102-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03190-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00517-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01165-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01160-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01702-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01032-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00249-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00512-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02579-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04495-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00957-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01714-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03624-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00599-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01011-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03840-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01997-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00625-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00881-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01971-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01716-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03069-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00017-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01165-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00625-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03630-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00436-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02573-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01053-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03743-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00401-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00517-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02010-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04126-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01037-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01011-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01052-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00885-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02613-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03426-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03006-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01051-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01124-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00599-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00249-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02589-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01036-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01662-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00622-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01158-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03665-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02579-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01702-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00928-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02118-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00954-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01012-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03853-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03129-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03628-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03635-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03211-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01689-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03129-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01052-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03356-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01054-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03632-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01052-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03190-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03126-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01011-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01053-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03635-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01383-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02116-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01907-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02010-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00277-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00625-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04473-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00957-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03061-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00401-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00017-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02613-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01032-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01036-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02697-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00518-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03840-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01378-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00516-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00599-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00709-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01687-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01381-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02118-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00622-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01715-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00881-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02116-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04848-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03639-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03086-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02610-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03632-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01379-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01971-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00881-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02768-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01051-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02899-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03839-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01687-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01662-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00302-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03632-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03123-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03173-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03624-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04119-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00709-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03350-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00954-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01012-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03061-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03670-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03743-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02940-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01687-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02463-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00598-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03123-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01998-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03439-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00249-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03639-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04495-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00512-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00513-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00957-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01031-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01971-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01011-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03395-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02115-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01719-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03356-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02939-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01703-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00954-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04848-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03069-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01031-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00017-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02116-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01379-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01687-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00885-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01897-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00599-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00513-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02573-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01998-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03630-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01702-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02109-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04848-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02944-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00198-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03007-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03628-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00514-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03061-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03778-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03884-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02809-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02115-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01379-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01719-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02585-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03428-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01703-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03743-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01052-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01167-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02463-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03635-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00277-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01166-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03086-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01598-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00598-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03839-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00957-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02109-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00819-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02112-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00928-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00302-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02115-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00102-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03006-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04027-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03670-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03395-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01037-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00589-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02768-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03840-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02606-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01897-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00249-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03428-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03839-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02998-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00189-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01032-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01012-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00589-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03743-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00954-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02069-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01453-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00640-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02890-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03039-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03000-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01382-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01907-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03069-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00395-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02112-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04479-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01637-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02890-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01703-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02591-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01453-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04072-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04479-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04475-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00514-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00885-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04473-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02610-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03123-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02010-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03395-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01169-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00102-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00881-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00640-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01453-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02115-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00198-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00189-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03754-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02610-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00625-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03350-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00640-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01714-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04853-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-03624-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01328-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-01453-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03039-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01166-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01167-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01375-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-04282-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02701-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03039-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-04853-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-02590-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01011-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00395-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-01168-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-00189-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-00303-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03884-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3L-02112-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/PDA/C3N-03853-23.svs
