curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00843-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00855-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03914-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02630-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03230-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03087-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03208-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03087-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02934-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01601-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00645-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01056-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04158-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00645-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02854-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02064-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01056-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04349-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01002-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03953-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00564-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01535-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00754-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03221-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-05041-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01914-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04164-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03641-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03403-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04164-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00754-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03232-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00645-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03227-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03166-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00855-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01914-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00035-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01535-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03236-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01706-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04158-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00567-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03366-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01532-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02359-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04492-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03615-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00567-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02630-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00567-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02851-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04492-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03641-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01002-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01551-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02533-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01038-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03615-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04349-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03200-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00645-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01002-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02038-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02630-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00171-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00171-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01534-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01534-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03253-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01038-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03953-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03227-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03641-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04492-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01535-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03230-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04158-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-05041-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00567-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01883-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02340-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01535-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02359-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03647-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02942-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02034-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03232-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01883-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03068-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01523-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03489-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03232-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04349-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03647-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02213-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01883-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03068-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02034-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02846-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03230-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02103-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01466-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03366-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02722-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04492-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00855-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03214-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00564-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03236-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03914-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01059-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03403-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01914-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00035-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03647-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01059-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03214-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00754-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02213-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03221-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03366-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03208-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02038-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03641-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03087-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00754-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01523-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00171-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04164-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02630-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03960-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01534-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01059-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02359-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02103-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03615-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02038-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03914-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02064-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02034-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01601-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02852-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01038-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03196-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03200-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01706-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03214-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02103-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03230-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01523-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00564-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03615-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03641-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03197-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02334-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01601-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00843-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00853-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03221-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03166-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01523-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01532-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02203-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01601-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04349-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02334-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02103-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00171-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03227-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03403-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02340-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02851-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00171-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00853-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03236-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02340-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03221-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02846-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02942-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04164-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02722-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04349-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-00029-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02533-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03647-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01532-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00855-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00853-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00853-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02359-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02064-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00875-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00875-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00645-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03489-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02334-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03914-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00843-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03960-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02034-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02533-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01534-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03236-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04164-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02630-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03068-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00754-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02722-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02942-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03489-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01532-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01574-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01883-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04492-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01914-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03232-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03198-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02340-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03489-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03227-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03196-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02203-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03641-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02334-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01056-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03253-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00645-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03221-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00171-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-00843-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03208-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02934-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-02103-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03956-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-01534-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02722-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-03956-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02038-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02064-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-04492-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3L-01551-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-04158-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03221-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-03096-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/SAR/C3N-02934-22.svs
