curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03589-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03264-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01764-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00743-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02062-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02468-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01633-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01256-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00753-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01307-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00388-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03044-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00155-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01874-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02635-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00848-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02744-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00098-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01847-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00771-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02027-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02802-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01003-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02337-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01267-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01275-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01876-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01830-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00938-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01821-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00601-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00139-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02632-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01631-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01248-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01346-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02012-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00946-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02357-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02411-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00866-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02061-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00850-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02800-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03044-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00769-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01604-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02746-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01249-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00601-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03467-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05848-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01525-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02595-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00858-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02337-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01864-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01342-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00563-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02637-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00769-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01848-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01510-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02249-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00151-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01217-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00753-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01219-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01079-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01246-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01880-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02412-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02744-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01520-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01355-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01525-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03044-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01664-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01604-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03589-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00586-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01802-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01825-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02602-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01537-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00932-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05848-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02436-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00090-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01877-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01247-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02632-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01848-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02409-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02253-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00145-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01821-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01284-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00520-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01913-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02399-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01217-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01821-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03044-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00358-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01873-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00379-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02449-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02030-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00563-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01284-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01267-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00729-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00136-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01875-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00340-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02347-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01668-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03152-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02403-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02372-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00155-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02382-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01967-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01064-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02061-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01925-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02357-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03467-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00850-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00918-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00358-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01880-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02298-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00847-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00008-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00946-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02639-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01510-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01304-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02028-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00866-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01257-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02296-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02595-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00729-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02545-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01879-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01529-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01172-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01252-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01876-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01211-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00358-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01537-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00836-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00605-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02392-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03594-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01064-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01925-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01766-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05571-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01282-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00753-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00520-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02274-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01763-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02598-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02411-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02678-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02408-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01825-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02747-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01633-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02353-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02602-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02247-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00361-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00386-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00743-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01311-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00767-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02678-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01744-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02125-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00449-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02448-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00157-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00333-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01212-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01344-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01267-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01631-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02631-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00732-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01830-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01526-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00836-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01346-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02449-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00858-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00361-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05571-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01874-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00449-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00362-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01525-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02027-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01874-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00151-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00750-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02557-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01871-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01967-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01749-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00333-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01878-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01967-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00586-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01212-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01267-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00200-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00866-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02437-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02271-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00388-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00413-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01267-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05571-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01871-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01008-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02557-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02357-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05849-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01212-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02271-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01510-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02979-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00848-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00356-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01764-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01275-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02555-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00734-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00340-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03594-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01064-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00943-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02125-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01739-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01001-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01925-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02253-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00008-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00872-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00732-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02744-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00729-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00333-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01729-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02028-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01355-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00860-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01253-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01079-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01341-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02027-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03264-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02244-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02408-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00905-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00850-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01211-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03264-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02347-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00858-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01631-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01864-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00137-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02555-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01311-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01913-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02354-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03264-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01008-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01003-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00386-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02296-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00356-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01249-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02389-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00734-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01526-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02947-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00586-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00880-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01765-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01843-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02746-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02972-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00860-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00155-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01248-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01219-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00098-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01672-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01217-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00340-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00872-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01526-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02976-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00006-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01521-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01833-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01219-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00156-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00321-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01732-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00333-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01766-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02412-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02802-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01171-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01304-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00947-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01633-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00143-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01521-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01312-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00388-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00755-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01761-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00333-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00362-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02468-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00520-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02802-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01172-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01875-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03044-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00200-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01967-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01880-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01346-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01526-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01764-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02409-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00962-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00942-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00362-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02636-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00770-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00962-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02244-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00156-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01864-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00750-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00938-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02972-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01079-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00734-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02411-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00734-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01873-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02247-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01256-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01307-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01732-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02635-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00963-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02602-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01001-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00921-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00859-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00136-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02947-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02062-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00905-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00136-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00379-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01064-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01355-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01604-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02353-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00137-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00563-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02412-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02253-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01761-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00729-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02631-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00859-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01537-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00136-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01525-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02372-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02976-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02061-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01664-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02253-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03152-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02468-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01211-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01664-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02545-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01520-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01219-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00872-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01307-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02298-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00949-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05849-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02635-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02744-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01871-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01871-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00847-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01825-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02274-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00386-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02746-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00006-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00961-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00743-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00771-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02247-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02631-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02384-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01802-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01840-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02436-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01825-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02372-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01864-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00836-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01599-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02545-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00086-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00413-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01349-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02395-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05849-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01967-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03143-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02408-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02354-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00753-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01217-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00942-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02802-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02437-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00098-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00836-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01520-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02953-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02741-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01079-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00151-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00860-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00388-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01064-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01878-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00333-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02274-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01664-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03589-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01875-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01763-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01007-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03467-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02747-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01877-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02244-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01840-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03589-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02468-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00379-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01639-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00601-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00339-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02637-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01879-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00340-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02244-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02296-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02125-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00860-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00139-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02894-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02271-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02802-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02744-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03143-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01344-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00943-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01873-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00388-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01521-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01604-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02027-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00743-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00200-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02598-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02247-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01840-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03467-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03767-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03415-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01349-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00586-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03264-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00858-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01668-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02062-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02382-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00755-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01274-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02436-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01765-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00860-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01847-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02436-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01355-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02062-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02357-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03594-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00151-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00898-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01282-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00880-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02403-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00520-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02216-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01252-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02298-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01355-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00755-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00155-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02409-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02354-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01212-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00413-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01284-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02125-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01873-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02990-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02639-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00321-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01307-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02302-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01879-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01253-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02216-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01729-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01765-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02741-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01764-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02972-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02337-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00161-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02347-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01537-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00334-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01079-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01847-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00947-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00321-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02408-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00032-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00200-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02372-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00905-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01833-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02947-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00848-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00386-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02802-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01599-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00156-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01529-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00145-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01520-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00328-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02595-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01510-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05571-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02994-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00859-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00767-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01344-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02302-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00145-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00520-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00601-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00143-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02972-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00859-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02972-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00321-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02382-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02741-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02545-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00379-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02468-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01739-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00848-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01277-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02216-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01171-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02030-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02384-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01848-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02557-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02602-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00963-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00847-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02061-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05849-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01967-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02747-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02978-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00151-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02437-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01521-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01871-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00932-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02382-30.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01529-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01257-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00326-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01830-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00151-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01763-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01355-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01246-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02468-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00836-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01843-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01639-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01211-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00155-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02012-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00605-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00323-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02746-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02030-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00880-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01599-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01510-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01312-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01211-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02947-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01761-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01344-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02382-29.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00361-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00872-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00858-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02247-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01876-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00961-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02409-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00732-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00086-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02436-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02448-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01821-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00850-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01749-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00781-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02337-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02789-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01840-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02976-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00732-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01312-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00143-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01764-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00200-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02636-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01211-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00770-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02741-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03044-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02598-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02636-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01277-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00090-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01284-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01342-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01633-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00137-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01843-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01843-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02028-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01304-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01925-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-28.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03264-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01304-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00340-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00377-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02119-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02392-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00139-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00389-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00563-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00356-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02121-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-05571-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00321-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02389-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02437-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00157-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02302-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00337-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02249-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02125-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00356-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01848-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02411-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00155-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00383-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00949-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00921-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02746-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01529-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00921-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00755-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03005-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-03417-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00880-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02028-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-03594-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00859-25.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00386-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-01744-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00324-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02412-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00780-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02953-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-02557-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02637-21.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00847-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00321-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00866-23.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02030-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3L-00032-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00335-26.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-02947-27.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01878-22.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-01079-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00322-24.svs
curl -LOC - https://pathology.cancerimagingarchive.net/download/UCEC/C3N-00729-26.svs
